spring:
  application:
    name: ahun-duty-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ahun_duty}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  flyway:
    clean-on-validation-error: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
ahun:
  cards:
    templates-path: ${CARDS_TEMPLATES_PATH:/home/petrolal/Documents/AhunDocs}

petrolal:
  commons:
    web:
      swagger:
        title: Ahun Duty Service
        description: Service to generate and maintain duty
        version: "1.0"

