[versions]
kotlin = "2.1.0"
springBoot = "3.3.5"
springDependencyManagement = "1.1.7"
pdfbox = "3.0.4"
flyingSaucerCore = "9.1.22"
kotlinMockito = "5.4.0"
springCommonsWeb = "2.4.0"

[libraries]
# Spring Boot Starters & Database
spring-boot-starter-thymeleaf = { group = "org.springframework.boot", name = "spring-boot-starter-thymeleaf" }
kotlin-mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "kotlinMockito" }

kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5" }
petrolal-commons-web = { module = "com.petrolal.commons.web:spring-commons-web", version.ref = "springCommonsWeb" }

# Card generation
xhtmlrenderer-flyingSaucerCore = { group = "org.xhtmlrenderer", name = "flying-saucer-core", version.ref = "flyingSaucerCore" }
xhtmlrenderer-flyingSaucerPdfOpenpdf = { group = "org.xhtmlrenderer", name = "flying-saucer-pdf-openpdf", version.ref = "flyingSaucerCore" }
apache-pdfbox = { group = "org.apache.pdfbox", name = "pdfbox", version.ref = "pdfbox" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }

